student:main.o addmiddle.o deleteall.o reverse_list.o student_exit.o student_save.o count.o sort_list.o student_delete.o student_modification.o student_show.o
	cc main.c addmiddle.c deleteall.c reverse_list.c student_exit.c student_save.c count.c sort_list.c student_delete.c student_modification.c student_show.c -o student

main.o:main.c
	cc -c main.c
addmiddle.o:addmiddle.c
	cc -c addmiddle.c
deleteall.o:deleteall.c
	cc -c deleteall.c
reverse_list.o:reverse_list.c
	cc -c reverse_list.c
student_exit.o:student_exit.c
	cc -c student_exit.c
student_save.o:student_save.c
	cc -c student_save.c
count.o:count.c
	cc -c count.c
sort_list.o:sort_list.c
	cc -c sort_list.c
student_delete.o:student_delete.c
	cc -c student_delete.c
student_modification.o:student_modification.c
	cc -c student_modification.c
student_show.o:student_show.c
	cc -c student_show.c

